services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres: