# Generated by Django 5.1.3 on 2024-11-19 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=20, null=True)),
                ("rows", models.PositiveSmallIntegerField()),
                ("columns", models.PositiveSmallIntegerField()),
                ("mines", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("custom", "Custom"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField()),
                ("column", models.PositiveSmallIntegerField()),
                ("is_mine", models.BooleanField(default=False)),
                ("is_revealed", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("adjacent_mines", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "row", "column")},
            },
        ),
    ]
